server:
  port: 8200

spring:
  application:
    name: admin-service

  datasource:
    url: ${OAUTH_DB_URL:jdbc:postgresql://localhost:55432/identity_db}
    username: ${OAUTH_DB_USERNAME:postgres}
    password: ${OAUTH_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          admin-service-client:
            provider: spring
            client-id: admin-service
            client-secret: admin-secret
            authorization-grant-type: client_credentials
            scope: internal.read,internal.write
        provider:
          spring:
            issuer-uri: ${AS_ISSUER_URI:http://localhost:9000}
    

management:
  endpoints:
    web:
      exposure:
        include: health,info

admin:
  api-user:
    username: ${ADMIN_API_USERNAME:admin}
    password: ${ADMIN_API_PASSWORD:admin-secret}
  seed-client:
    client-id: ${BFF_CLIENT_ID:exam-bff-client}
    client-secret: ${BFF_CLIENT_SECRET:exam-bff-secret}
    redirect-uris:
      - ${BFF_REDIRECT_URI:http://localhost:8080/api/auth/callback/exam-oidc}
    post-logout-redirect-uris:
      - ${BFF_LOGOUT_REDIRECT:http://localhost:8080}
    scopes:
      - openid
      - profile
      - exam.read
      - exam.write
      - offline_access

